import React from "react";
import Navbar from "../components/Navbar";
import Head from "next/head";
import { Footer } from "../components/Footer";
import styles from "../pages/index.module.scss";

export function IndexLayout(props) {
  return (
    <>
      <Head>
        <title>Groupomania</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
      </header>
      <main className={styles.indexLayout}>{props.children}</main>
      <footer>
        <Footer />
      </footer>
    </>
  );
}
